Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'namespace', 'after', 'task', 'aasm']
  Exclude:
    - "config/deploy.rb"
    - "app/admin/**/*rb"

Style/AccessorMethodName:
  Exclude:
    - "app/controllers/*.rb"

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*.rb"

Metrics/ClassLength:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - $redis

AllCops:
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.3
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "spec/factories/**/*.rb"

Lint/UnneededDisable:
  Enabled: false
  AutoCorrect: false

Lint/UnusedMethodArgument:
  Enabled: true
  AutoCorrect: false

Lint/UnusedBlockArgument:
  Enabled: true
  AutoCorrect: false

Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/EmptyMethod:
  Enabled: true
  AutoCorrect: false

Style/ClassAndModuleChildren:
  Enabled: false
